# This file contains default non-project-specific settings for 'stack', used
# in all projects.  For more information about stack's configuration, see
# http://docs.haskellstack.org/en/stable/yaml_configuration/

# The following parameters are used by "stack new" to automatically fill fields
# in the cabal config. We recommend uncommenting them and filling them out if
# you intend to use 'stack new'.
# See https://docs.haskellstack.org/en/stable/yaml_configuration/#templates
templates:
  params:
   author-name: Will Bush
   author-email: will.g.bush@gmail.com
   copyright: MIT
   github-username: willbush

nix:
  enable: true
  packages: [zlib.dev, zlib.out]
